
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 01 15:18:26 CET 2016
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 25;
  public static final int EGAL = 21;
  public static final int OU = 19;
  public static final int PLUS = 8;
  public static final int SUP = 14;
  public static final int MCECRIRE = 22;
  public static final int VIRGULE = 24;
  public static final int NON = 20;
  public static final int POINTVIRGULE = 23;
  public static final int MOINS = 9;
  public static final int INF = 15;
  public static final int PARFER = 13;
  public static final int ENTIER = 5;
  public static final int EOF = 0;
  public static final int MULT = 10;
  public static final int EGALEGAL = 16;
  public static final int DIV = 11;
  public static final int CONSTANTEBOOL = 27;
  public static final int ET = 18;
  public static final int error = 1;
  public static final int PRIVEE = 4;
  public static final int PAROUV = 12;
  public static final int CONSTANTECHAINE = 28;
  public static final int DIFF = 17;
  public static final int CONSTANTEINT = 26;
  public static final int DEBUT = 6;
  public static final int MCCLASSE = 2;
  public static final int FIN = 7;
  public static final int PUBLIQUE = 3;
}

