
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 02 16:55:56 CET 2016
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 23;
  public static final int EGAL = 19;
  public static final int OU = 17;
  public static final int PLUS = 6;
  public static final int SUP = 12;
  public static final int STATUT = 27;
  public static final int MCECRIRE = 20;
  public static final int VIRGULE = 22;
  public static final int NON = 18;
  public static final int POINTVIRGULE = 21;
  public static final int MOINS = 7;
  public static final int INF = 13;
  public static final int PARFER = 11;
  public static final int ENTIER = 3;
  public static final int EOF = 0;
  public static final int MULT = 8;
  public static final int EGALEGAL = 14;
  public static final int DIV = 9;
  public static final int CONSTANTEBOOL = 25;
  public static final int ET = 16;
  public static final int error = 1;
  public static final int PAROUV = 10;
  public static final int CONSTANTECHAINE = 26;
  public static final int DIFF = 15;
  public static final int CONSTANTEINT = 24;
  public static final int DEBUT = 4;
  public static final int MCCLASSE = 2;
  public static final int FIN = 5;
}

