
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 02 17:18:18 CET 2016
//----------------------------------------------------

package plic.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 21;
  public static final int EGAL = 17;
  public static final int OU = 15;
  public static final int PLUS = 4;
  public static final int SUP = 10;
  public static final int STATUT = 25;
  public static final int MCECRIRE = 18;
  public static final int VIRGULE = 20;
  public static final int NON = 16;
  public static final int POINTVIRGULE = 19;
  public static final int MOINS = 5;
  public static final int INF = 11;
  public static final int PARFER = 9;
  public static final int TYPE = 26;
  public static final int EOF = 0;
  public static final int MULT = 6;
  public static final int EGALEGAL = 12;
  public static final int DIV = 7;
  public static final int CONSTANTEBOOL = 23;
  public static final int ET = 14;
  public static final int error = 1;
  public static final int PAROUV = 8;
  public static final int CONSTANTECHAINE = 24;
  public static final int DIFF = 13;
  public static final int CONSTANTEINT = 22;
  public static final int MCCLASSE = 2;
  public static final int FIN = 3;
}

